#hlive_homepage:
 #   path: /hello/{nom}/{prenom}
  #  defaults: { _controller: HliveBundle:Default:index }

#accueil:
 #   path: /
  #  defaults: { _controller: HliveBundle:Accueil:index }   
accueil:
    path: /accueil
    defaults: { _controller: HliveBundle:Accueil:index }
direct:
    path: /direct
    defaults: { _controller: HliveBundle:Direct:index }

programme:
    path: /programme
    defaults: { _controller: HliveBundle:Programme:index }

contact:
    path: /contact
    defaults: { _controller: HliveBundle:Contact:index } 
#fos_user_security:
#    resource: routing/security.yml
#    prefix: /
#fos_user_profile:
#    resource: routing/profil.yml
#    prefix: /compte

#fos_user_register:
#    resource: routing/inscription.yml
#    prefix: /inscription

#fos_user_resetting:
#    resource: routing/resetting.yml
#    prefix: /resetting

#fos_user_change_password:
#    resource: routing/change_mot_passe.yml
#    prefix: /compte