#HliveBundle\Entity\Annonce:
    type: entity
    table: annonce
    #repositoryClass: HliveBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            nullable: false
            length: 128
            fixed: false
            comment: ''
        contenu:
            type: text
            nullable: false
            fixed: false
            comment: ''
        date_add:
            type: datetime
        date_update:
            type: datetime
        active:
            type: boolean
            nullable: false
            length: 5
            fixed: false
            option:
               default: 0
        
    lifecycleCallbacks: {  }
