HliveBundle\Entity\Media:
    type: entity
    table: media
    #repositoryClass: HliveBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            nullable: false
            length: 164
            fixed: false
            comment: ''
        contenu:
            type: text
            nullable: false
            fixed: false
            comment: ''
        description:
            type: text
            nullable: false
            fixed: false
            comment: ''
        lien_media:
            type: string
            nullable: false
            length: 164
            fixed: false
            comment: ''
        duree:
            type: string
            nullable: false
            length: 12
            fixed: false
            comment: ''
        date_add:
            type: datetime
        date_update:
            type: datetime
        nbre_commentaire:
            type: integer
            nullable: false
            option:
               unsigned: true
               default: 0
        active:
            type: boolean
            nullable: false
            length: 5
            fixed: false
            option:
               default: 0
        
    lifecycleCallbacks: {  }
