HliveBundle\Entity\Page:
    type: entity
    table: page
    #repositoryClass: HliveBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        slug:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
