HliveBundle\Entity\Pays:
    type: entity
    table: pays
    #repositoryClass: HliveBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        
    lifecycleCallbacks: {  }

