HliveBundle\Entity\Region:
    type: entity
    table: region
    #repositoryClass: HliveBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        
    lifecycleCallbacks: {  }

