HliveBundle\Entity\TypeMedia:
    type: entity
    table: type_media
    #repositoryClass: HliveBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
        description:
            type: text
            nullable: false
            fixed: false
            comment: ''
        
    lifecycleCallbacks: {  }
