HliveBundle\Entity\User:
    type: entity
    table: fos_user
    #repositoryClass: HliveBundle\Repository\CommentaireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        
    lifecycleCallbacks: {  }
